name: Create Release

on:
  push:
    branches:
      - master
    paths:
      - '**/*.wixproj'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install xmlstarlet
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet

      - name: Extract version from .wixproj
        id: version
        run: |
          FILE="./WiX/WiX.wixproj"
          VERSION=$(xmlstarlet sel -t -v "//Version" "$FILE")
          echo "Version from .wixproj: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
